# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0003_auto_20160204_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='salutation',
            new_name='application',
        ),
    ]
